#ifndef C_CONST_H
#define C_CONST_H

#define CORD_ORIGIN 0
#define NEIGHBOUR_SHIFT 1

#define ARROW_UP 72
#define ARROW_DOWN 80
#define ARROW_LEFT 75
#define ARROW_RIGHT 77
#define KEY_DOWN -32

#define PROBABILITY_SOW 1.0/2.0
#define TRY_DANDELION_TO_SOW_NUMBER 3
#define GUARANA_INCREASE_STRENGTH_WHO_EAT 3

#define PLANT_STRENGTH 0
#define NIGHTSHADE_STRENGTH 99
#define SOSNOWSKY_STRENGTH 10

#define HUMAN_STRENGTH 5
#define WOLF_STRENGTH 9
#define LAMP_STRENGTH 4
#define FOX_STRENGTH 3
#define TURTLE_STRENGTH 2
#define ANTELOPE_STRENGTH 4

#define PLANT_INITIATIVE 0

#define HUMAN_INITIATIVE 4
#define WOLF_INITIATIVE 5
#define LAMP_INITIATIVE 4
#define FOX_INITIATIVE 7
#define TURTLE_INITIATIVE 1
#define ANTELOPE_INITIATIVE 4

#define HUMAN_STEP 1
#define WOLF_STEP 1
#define LAMP_STEP 1
#define FOX_STEP 1
#define TURTLE_STEP 1
#define ANTELOPE_STEP 2

#define PROBABILITY_TURTLE_MOVE 3.0/4.0
#define STRENGTH_REPEL_ATTACK_TURTLE 5
#define PROBABILITY_ANTELOPE_ESCAPE 1.0/2.0

#define ALZUR_SHIELD_DURATION 5
#define ALZUR_SHIELD_DURATION_SET ALZUR_SHIELD_DURATION+1
#define ALZUR_SHIELD_LOCK 5

#endif //C_CONST_H
